### PR TITLE
Introduce Readme

### PR DESCRIPTION
**Pull request by dnltsk**
This PR introduces a Readme file that contains 
* a link to the making-of video on youtube  
* a sample photo of the cube

### CODE REVIEW

**Comment by varun169** [comment]
Can someone please tell how I can add identifiers to Arduinodroid software

**Comment by PARTHKALARIYA** [comment]
I Don't Know How To Install Arduino code In Arduino And Library File Install In To The Arduino Software.

**Comment by PARTHKALARIYA** [comment]
Which type Of switch is used.

**Comment by PARTHKALARIYA** [comment]
Where A Soldier Positive (+) And Negative (-) Supply to the circuit?

**Pull request closed without merging**
